package morago.enums;

public enum NotificationType {
    USER_REGISTERED,
    PROFILE_INCOMPLETE,
    PROFILE_VERIFIED,
    PROFILE_REJECTED,
    PROFILE_COMPLETED,
    PROFILE_UPDATED,
    PROFILE_DELETED,

    ADMIN_NEW_USER,
    ADMIN_PROFILE_REVIEW_REQUIRED,

    CALL_INCOMING,
    CALL_ACCEPTED,
    CALL_REJECTED,
    CALL_CANCELLED,
    CALL_ENDED,
    CALL_MISSED,

    SYSTEM_INFO,
    SYSTEM_WARNING
}
